#! /bin/sh
function_to_fork1() {
    sleep 0.5
    echo "+---------------------------------------------------+"
    echo "|                  ***   GDB  ***                   |"
    echo "+---------------------------------------------------+"
    gdb-multiarch
}

# ... execution continues in parent process ..

function_to_fork2() {
    echo "+---------------------------------------------------+"
    echo "|              ***  OPENOCD   ***                   |"
    echo "+---------------------------------------------------+"
    "/usr/bin/openocd" "-c" "gdb_port 50000" "-s" "/usr/share/openocd/scripts" "-f" "./lib/stlink.cfg" "-f" "./lib/stm32h7x.cfg" 
}

function_to_fork2 &
#pidApp1=$!
#echo $pidApp1
function_to_fork1 
#kill -9 $pidApp1
killall -9 openocd
sleep 0.1
echo "+---------------------------------------------------+"
echo "|         ***  OPENOCD  KILLED ***                  |"
echo "+---------------------------------------------------+"
